### ISSUE TITLE
IE10 and IE11 VMs are IE9

### ISSUE THREAD

**Issue by kud** [xdissent/ievms#174]
No idea why but on IE10 and IE11 VMs, it's IE9. No update from ievms. I installed it via your script and via iectrl, it installed them 3 times and nothing, still ie9. Do you have any idea why?

**Comment by rocketraman** [comment]
I'm having this problem on VirtualBox 4.3 also. Fedora 21. The output is:

```
Successfully imported the appliance.
Building IE11 - Win7 VM
build_ievm_ie11
Found ievms control ISO at /home/raman/.ievms/ievms-control-0.2.1.iso - skipping download
MD5 check succeeded for /home/raman/.ievms/ievms-control-0.2.1.iso
Attaching ievms control ISO
Starting VM IE11 - Win7
Waiting for VM "IE11 - Win7" to power on...
VM "IE11 - Win7" has been successfully started.
Waiting for IE11 - Win7 to shutdown...
Waiting for IE11 - Win7 to shutdown...
Ejecting ievms control ISO
Attaching Guest Additions
VBoxManage: error: Cannot find the Guest Additions ISO image
```

**Comment by rocketraman** [comment]
For whatever reason VirtualBox 4.3 is having issues mounting the guest additions ISO. I was able to work around it by starting the partially created IE11 VM and doing `Devices - Insert Guest Additions ISO Image` before the boot completed, which causes VirtualBox to download the ISO, attach it, and install it.

Then, modify the `ievms.sh` script to not bail out because the IE11 VM already exists, but instead continue the installation of IE11, with the following patch:

```
--- ievms.sh.orig	2015-07-08 20:37:17.721841729 -0400
+++ ievms.sh	2015-07-08 20:39:35.248743125 -0400
@@ -461,7 +461,7 @@
 
 # Build the IE11 virtual machine, reusing the Win7 VM always.
 build_ievm_ie11() {
-    boot_auto_ga "IE11 - Win7"
+    #boot_auto_ga "IE11 - Win7"
     install_ie_win7 "IE11 - Win7" "http://download.microsoft.com/download/9/2/F/92FC119C-3BCD-476C-B425-038A39625558/IE11-Windows6.1-x86-en-us.exe" "7d3479b9007f3c0670940c1b10a3615f"
 }
 
@@ -479,7 +479,7 @@
 for ver in ${IEVMS_VERSIONS:-$all_versions}
 do
     log "Building IE${ver} VM"
-    build_ievm $ver
+    build_ievm_ie11
 done
 
 # We made it!
```

After running the patched ievms.sh, the IE11 update executable should now be on the VM desktop and can then be run manually.
