### ISSUE TITLE
Failed to download from the unarchiver (curl error code 52)

### ISSUE THREAD

**Issue by jansensan** [xdissent/ievms#236]
I am trying to run this command by following the instructions:

`curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | env IEVMS_VERSIONS="7 8 9" bash`

However after a really short moment, this is what I face: 

```
Downloading unar from http://theunarchiver.googlecode.com/files/unar1.5.zip to unar1.5.zip (attempt 1 of 3)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
````

If I use this URL directly in the browser, I can reach the file. I am not sure what is happening here, is this related to the IEVMS install script, or something else?

**Comment by xdissent** [comment]
Anyone still seeing this?

**Comment by badrinathvm** [comment]
I am facing the issue , Any resolution ?

**Comment by krebs666** [comment]
Download ievms script by:

`curl -O https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh`

edit to look like (lines starting with line numbers as of date of post - they will most probable change in the future):

```
164 # Download and install `unar` from Google Code.
165 install_unar() {
166 #    local url="http://theunarchiver.googlecode.com/files/unar1.5.zip"
167     local url="http://wakaba.c3.cx/releases/TheUnarchiver/unar1.10.1.zip"
168     local archive=`basename "${url}"`
169 
170     download "unar" "${url}" "${archive}" "d548661e4b6c33512074df81e39ed874"
```

start install:
`bash ievms.sh`

**Comment by billyromano** [comment]
The fix works, however, there is another issue after you apply the fix of the 'unar1.10.1.zip' that @krebs666 mentioned. There is a new download URL that Microsoft is using. You'll need to update the ievms.sh file in order to properly download the vm's.

Issue that happens when you run `bash ievms.sh`:
`Failed to download http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/IE6_WinXP.zip`

The base URL should be changed to this:
`https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/`

Here's what you update in the code (search and replace):
previous: `url="http://virtualization.modern.ie/vhd/IEKitV1_Final/VirtualBox/OSX/${archive}"`
fix: `url="https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/${archive}"`
