### ISSUE TITLE
Get IE11 even when when reuse_win7=no

### ISSUE THREAD

**Issue by arthurlogilab** [xdissent/ievms#248]
I'm not sure I understand why ievms cannot get IE11 without reusing win7. 

IE11 on Win10 https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE11/Linux/IE11.Win10.For.Linux.VirtualBox.zip

or 

IE11 on Win8.1 https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE11/Linux/IE11.Win8.1.For.Linux.VirtualBox.zip

could be used, couldn't they ?

**Comment by xdissent** [comment]
They could! Those images are new, though, (or at least did not exist as single zip files until recently) so they aren't integrated into ievms yet. It'd be pretty easy to add them, but since MS just updated all their modern.IE stuff and ievms was initially written at a time when there were very weird, specific version constraints that are no longer relevant, it's probably time for a bit of a refactor to support all the new options. I plan on getting to that as soon as this weekend, but pull requests are always welcome in the meantime.

Also, a brief thank you to MS for considering community feedback in their recent updates (probably from many ievms users) - especially single zip files! That's going to make ievms a lot more flexible and easier to maintain.

**Comment by grayghostvisuals** [comment]
@xdissent Couldn't agree more. Thanks for the work you do to keep this project going as well. :beers: :beers:

**Comment by xdissent** [comment]
For reference, the new images were set up differently and presented problems getting vbox guest additions to cooperate. The old images are fine, many people already have them locally, reusing saves tons of space, and we even have MS Edge now.
