### ISSUE TITLE
Seamless Mode Not Seamless for MSEdge

### ISSUE THREAD

**Issue by dennisgaebel** [xdissent/ievms#268]
Edge uses 1024 x 768 resolution which is the highest resolution offered in the VMs display settings and refuses to have a seamless mode.

![screen shot 2015-08-24 at 2 01 45 am](https://cloud.githubusercontent.com/assets/13485205/9433754/cd289c9c-4a04-11e5-8d7e-553abf836ffa.png)

**Comment by xdissent** [comment]
Yeah, apparently the win10 vm defaults to 8mb video memory. You can change it manually in Virtualbox for now, but I'll be pushing an update that sets it to 32mb upon creation.

**Comment by dennisgaebel** [comment]
:+1: thanks so much!

**Comment by xdissent** [comment]
Tracking this in #266

**Comment by jcowhigjr** [comment]
The video memory setting was a problem.  However, I think that "seamless mode" still will not work for for the current win10 vm (64bit). Entering seamless mode, I see a black overlay of the whole screen instead of seamless application windows.  I am on a 64bit ubuntu host.

  https://forums.virtualbox.org/viewtopic.php?f=2&t=69589&p=333726&hilit=seamless+mode#p333726
